services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - ./my-app/.env.local
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
